server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/celotts/config-server-repo.git
          clone-on-start: true

  main:
    allow-bean-definition-overriding: true
    web-application-type: none  # 🚨 Evita que levante un servidor web innecesario

logging:
  level:
    org.springframework: INFO
