server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/celotts/config-server-repo.git
          clone-on-start: true

  # 🚨 Deshabilitar la conexión a la base de datos en Config Server
  datasource:
    url: ""
    username: ""
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false

logging:
  level:
    org.springframework: INFO