server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/celotts/config-server-repo.git
          clone-on-start: true

  # Deshabilitar DataSource en Config Server
  datasource:
    url: ""
    username: ""
    password: ""

logging:
  level:
    org.springframework: INFO