server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/celotts/config-server-repo.git
          clone-on-start: true

# 🔹 Deshabilitar la configuración de base de datos en Config Server
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: ""
