spring:
  datasource:
    url: jdbc:postgresql://db:5432/patient_db
    username: patient_user
    password: patient_password
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: patient-service