spring:
  datasource:
    url: jdbc:postgresql://db:5432/patient_db
    username: appointments_dev
    password: 0513Appointments_dev
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: patient-service